### ISSUE TITLE
windows dev issue

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [vstinner/cpython_core_tutorial#14]
i'd like to ask some issues for windows

- in the tuto, vs2015 is recommended. can someone use vs2017?
- in the tuto, x64 is used to build, can someone use x32 if his pc is x32 or the project is a x64  only project

**Comment by matrixise** [comment]
Hi @Abdur-rahmaanJ 

The project is not specific to a 64bit architecture, for example, there are packages for Windows 32bits , https://www.python.org/downloads/release/python-372/

For the compiler, there is a recommendation for VisualStudio 2017, and you can download it.

https://devguide.python.org/setup/#windows

> Python 3.6 and later can use Microsoft Visual Studio 2017. You can download and use any of the free or paid versions of Visual Studio 2017.
>
> When installing Visual Studio 2017, select the Python development workload and the optional Python native development tools component to obtain all of the necessary build tools. If you do not already have git installed, you can find git for Windows on the Individual components tab of the installer.


Have a nice day

**Comment by Abdur-rahmaanJ** [comment]
i mean on this tuto of ours

**Comment by vstinner** [comment]
I reopen the issue. The tutorial says nothing about VS 2017.

**Comment by vstinner** [comment]
> in the tuto, vs2015 is recommended. can someone use vs2017?

Yes. I updated the tutorial to mention VS 2017.

> in the tuto, x64 is used to build, can someone use x32 if his pc is x32 or the project is a x64 only project

You can build in 32-bit mode. On the command line, it's the "-p x86" option.
