### ISSUE TITLE
CI section is outdated

### ISSUE THREAD

**Issue by sobolevn** [vstinner/cpython_core_tutorial#31]
Thanks a lot for writing this guide! It is a good on-boarding document for new triagers!

But, looks like it is a bit outdated in some parts.
For example: https://cpython-core-tutorial.readthedocs.io/en/latest/continuous_integration.html (source: https://github.com/vstinner/cpython_core_tutorial/blob/main/continuous_integration.rst)

Problems:
- `travis-ci.yml` is no longer used
- GitHub Actions are not mentioned
- There are new buildbots (and probably there are old unused ones in the doc right now)

Do you need help with this guide? I have some free time to polish some pages if it is needed 🙂

**Comment by vstinner** [comment]
I marked that Travis CI has been removed in commit f5315ec6351d6ccbf05e0aeeb5b036e56a10ea49.

https://pythondev.readthedocs.io/ci.html doesn't list buildbot workers.

GitHub Actions is mentioned.
